"""
HTML report generation module for DocuCheck.
Generates a visual dashboard of verification results.
"""

def generate_report(claims, issues, external_checks, input_filename=""):
    """
    Generates a modern HTML report from analysis results.
    
    Args:
        claims (list): List of Claim objects (as dictionaries).
        issues (list): List of internal consistency issues/contradictions.
        external_checks (list): List of FactCheckResult objects (as dictionaries).
        input_filename (str): The name of the processed document.
        
    Returns:
        str: A complete HTML document string.
    """
    
    # 1. Build the Claims List (Ensuring correct key syntax)
    claim_items = "".join(
        [f"<li><p>{c['claim']} <span class='section'>({c.get('section', 'Unknown')})</span></p></li>" for c in claims]
    )

    # 2. Build the Internal Consistency Issues List
    issue_items = "".join(
        [f"<li class='issue'>{i}</li>" for i in issues]
    ) if issues else "<li class='ok'>✅ No internal contradictions found.</li>"

    # 3. Build the External Verification Cards
    external_items = ""
    valid, outdated, unknown = 0, 0, 0
    
    if not external_checks:
        external_items = "<p class='no-checks'>No external fact-checks performed.</p>"
    else:
        for e in external_checks:
            # Determine visual status based on Pydantic-validated results
            status_class = "unknown"
            status_text = "Unknown"
            latest_info = e.get('latest_info', 'No additional context provided.')
            
            if e.get("is_outdated") is True:
                status_class = "outdated"
                status_text = "Outdated"
                outdated += 1
            elif e.get("is_outdated") is False:
                status_class = "valid"
                status_text = "Valid"
                valid += 1
            else:
                unknown += 1
                
            external_items += f"""
            <div class="ext-card">
                <p><b>Claim:</b> {e.get('claim', 'N/A')}</p>
                <div class="status-box {status_class}"><strong>{status_text}</strong></div>
                <p><b>Analysis:</b> {latest_info}</p>
                <p><small>Confidence: {int(e.get('confidence_score', 0) * 100)}%</small></p>
            </div>"""

    # 4. Generate the Final HTML Document
    full_html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DocuCheck Audit Report - {input_filename}</title>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 40px auto; padding: 20px; background: #f9fafb; }}
            h1, h2 {{ color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }}
            .section {{ font-size: 0.8em; color: #6b7280; background: #f3f4f6; padding: 2px 6px; border-radius: 4px; }}
            .issue {{ color: #b91c1c; background: #fef2f2; padding: 10px; border-left: 4px solid #ef4444; margin-bottom: 10px; list-style: none; }}
            .ok {{ color: #047857; background: #ecfdf5; padding: 10px; border-left: 4px solid #10b981; list-style: none; }}
            .ext-card {{ background: white; border: 1px solid #e5e7eb; padding: 20px; border-radius: 8px; margin-bottom: 15px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
            .status-box {{ display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 0.875rem; margin: 10px 0; }}
            .valid {{ background: #dcfce7; color: #166534; }}
            .outdated {{ background: #fee2e2; color: #991b1b; }}
            .unknown {{ background: #f3f4f6; color: #374151; }}
            .summary-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px; }}
            .stat-card {{ text-align: center; padding: 15px; border-radius: 8px; background: #fff; border: 1px solid #e5e7eb; }}
            .stat-val {{ display: block; font-size: 1.5rem; font-weight: bold; }}
        </style>
    </head>
    <body>
        <h1>Audit Report: {input_filename}</h1>
        
        <div class="summary-grid">
            <div class="stat-card">Valid Claims <span class="stat-val" style="color: #166534;">{valid}</span></div>
            <div class="stat-card">Outdated/Inaccurate <span class="stat-val" style="color: #991b1b;">{outdated}</span></div>
            <div class="stat-card">Unverifiable <span class="stat-val">{unknown}</span></div>
        </div>

        <h2>Internal Consistency Check</h2>
        <ul>{issue_items}</ul>

        <h2>External Reality Check</h2>
        {external_items}

        <h2>Extracted Claims List</h2>
        <ul>{claim_items}</ul>

        <footer style="margin-top: 50px; text-align: center; color: #9ca3af; font-size: 0.8rem;">
            Generated by DocuCheck AI Verifier Engine
        </footer>
    </body>
    </html>
    """

    # THE FIX: This return statement was missing, causing the TypeError in __main__.py
    return full_html