"""
src/tree/state.py
-----------------
Shared state object for the plan-execute-verify pipeline.

This is the single source of truth that flows through every node.
All fields have defaults so nodes can update only what they touch.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Sub-structures
# ---------------------------------------------------------------------------

@dataclass
class ResearchAngle:
    """A single research angle generated by the Planner."""
    angle_id: str          # e.g. "angle_0", "angle_1"
    title: str             # short label
    description: str       # 1-2 sentence elaboration
    query: str             # search / analysis query for this angle


@dataclass
class Evidence:
    """Evidence gathered by the Executor for one angle."""
    angle_id: str
    source_titles: list[str]       # paper titles used
    summary: str                   # free-text summary of the evidence
    sandbox_stdout: str = ""       # quantitative output, if any
    sandbox_used: bool = False


@dataclass
class VerificationScore:
    """Verifier's assessment of one angle's evidence."""
    angle_id: str
    score: float           # 0.0–1.0  (strength of evidence)
    rationale: str
    passed: bool           # True if score >= threshold


@dataclass
class Claim:
    """A single verifiable claim extracted from evidence."""
    claim_id: str
    angle_id: str
    text: str              # the claim sentence
    source_titles: list[str]


@dataclass
class ClaimVerification:
    """Fact-checker's verdict on a single claim."""
    claim_id: str
    supported: bool
    confidence: float      # 0.0–1.0
    supporting_sources: list[str]
    contradicting_sources: list[str]
    verdict: str           # "SUPPORTED" | "REFUTED" | "UNVERIFIABLE"


# ---------------------------------------------------------------------------
# Main pipeline state
# ---------------------------------------------------------------------------

@dataclass
class ResearchState:
    """
    The agent's memory — read and written by every node in the pipeline.

    Lifecycle:
        topic         → set by caller before graph.run()
        papers        → set by caller (Stage 1 output)
        angles        → written by Planner node
        evidence      → written by Executor node (one entry per angle)
        scores        → written by Verifier node
        claims        → written by ClaimExtractor node
        verifications → written by FactChecker node
        output        → written by graph after final node
    """

    # ---- Inputs (set before the graph runs) ----
    topic: str = ""
    papers: list = field(default_factory=list)   # list[Paper] from Stage 1

    # ---- Planner outputs ----
    angles: list[ResearchAngle] = field(default_factory=list)

    # ---- Executor outputs ----
    evidence: list[Evidence] = field(default_factory=list)

    # ---- Verifier outputs ----
    scores: list[VerificationScore] = field(default_factory=list)

    # ---- ClaimExtractor outputs ----
    claims: list[Claim] = field(default_factory=list)

    # ---- FactChecker outputs ----
    verifications: list[ClaimVerification] = field(default_factory=list)

    # ---- Budget tracking ----
    budget_usd: float = 0.50          # total sandbox budget for this run
    spent_usd: float = 0.0            # accumulated sandbox spend

    # ---- Final structured output ----
    output: Optional[dict] = None     # produced by graph after all nodes

    # ---- Internal bookkeeping ----
    errors: list[str] = field(default_factory=list)   # non-fatal warnings / errors
    current_node: str = ""            # last node that touched state (for debugging)

    # ---- Configurable thresholds ----
    evidence_score_threshold: float = 0.3   # minimum score for an angle to pass
    max_angles: int = 3                     # planner caps output at this many

    def passed_angles(self) -> list[ResearchAngle]:
        """Return angles whose evidence score passed the threshold."""
        passed_ids = {s.angle_id for s in self.scores if s.passed}
        return [a for a in self.angles if a.angle_id in passed_ids]

    def supported_claims(self) -> list[ClaimVerification]:
        """Return only the claims verified as SUPPORTED."""
        return [v for v in self.verifications if v.verdict == "SUPPORTED"]

    def to_output_dict(self) -> dict:
        """Produce the structured evidence map consumed by Stage 5 (writer)."""
        return {
            "topic": self.topic,
            "angles": [
                {
                    "id": a.angle_id,
                    "title": a.title,
                    "description": a.description,
                }
                for a in self.angles
            ],
            "evidence": [
                {
                    "angle_id": e.angle_id,
                    "summary": e.summary,
                    "sandbox_used": e.sandbox_used,
                    "sources": e.source_titles,
                }
                for e in self.evidence
            ],
            "scores": [
                {
                    "angle_id": s.angle_id,
                    "score": s.score,
                    "passed": s.passed,
                    "rationale": s.rationale,
                }
                for s in self.scores
            ],
            "claims": [
                {
                    "id": c.claim_id,
                    "angle_id": c.angle_id,
                    "text": c.text,
                }
                for c in self.claims
            ],
            "verifications": [
                {
                    "claim_id": v.claim_id,
                    "verdict": v.verdict,
                    "confidence": v.confidence,
                    "supported_by": v.supporting_sources,
                }
                for v in self.verifications
            ],
            "budget": {
                "allocated_usd": self.budget_usd,
                "spent_usd": round(self.spent_usd, 6),
            },
            "errors": self.errors,
        }
